name: Release

on:
  push:
    branches:
      - release/v*.*.x

jobs:
  test:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Print Environment Info
        run: npx lerna info
        shell: bash

      - name: Publish packages from git
        run: npx lerna publish from-git
        shell: bash
